# Generated by Django 2.1.15 on 2020-04-04 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200403_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='userimages', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text="Required. Phone number must be entered in the format: '+77076143537'. Up to 15 digits allowed.", max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+77076143537' or '77076143537'. Up to 15 digits allowed.", regex='^\\+\\d{11}$')], verbose_name='Phone Number'),
        ),
    ]
